# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a4f3a8e5143b687304e16088dd81f7f767574f9cafd767aaad53eb884d91ed4d0c219c103457a7491bf3d61654b1f095b8e5ba985c98e0957a26c60eadc0286

test:
  secret_key_base: 04b52a0e6e88747c8e97f897726a5135f67cbb6632b6f7bd7f5bd33c1870c4546fe90ab5b90a7ea89c9c2d99c4c42c5581a5cbb3e680a1372c632156a5feda11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
